// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateScrollArea('scrollArea', { spacing: 4, hasVerticalScrollbar: true, autoHideScrollbars: true });
    CreateText('text', { text: 'Select which category will be displayed as a default:' });
    CreateShape('rectangleShape', { rightImageWidth: 1, leftImageWidth: 1 });
    CreateText('text4', { text: 'Created By: Chris Beauchamp' });
    CreateText('text5', { text: 'Click here to make a comment or request new features' });
    CreateText('text6', { text: 'Version 1.0' });
    CreateText('text8', { text: 'New Version Available!' });
    CreateText('text9', { text: 'Sample Ad Text Here' });
    CreateGlassButton('done', { text: 'Done' });
}
window.addEventListener('load', setupParts, false);
