// This file was generated by Dashcode from Apple Computer, Inc.
// You may edit this file to customize your Dashboard widget.

var myName,myPre,myPost;
var thisversion = '1.0';
function load()
{
	setupParts();
	var defEngine = widget.preferenceForKey('default_engine');
	if(!defEngine)
		widget.setPreferenceForKey('Google','default_engine');
	document.getElementById('search_image').src = 'Images/logos/'+defEngine+'.png';

	myName = widget.preferenceForKey('myName');
	myPre = widget.preferenceForKey('myPre');
	myPost = widget.preferenceForKey('myPost');
	
	document.getElementById('textfield').value = myName;
	document.getElementById('textfield4').value = myPre;
	document.getElementById('textfield6').value = myPost;
	
	loadVersions();
}

function remove() {}

function hide() {}

function show() {}

function showBack(event)
{
	var front = document.getElementById("front");
	var back = document.getElementById("back");

	if (window.widget)
		widget.prepareForTransition("ToBack");

	if(document.getElementById('opt_container'))
		document.getElementById('front').removeChild(document.getElementById('opt_container'));

	front.style.display="none";
	back.style.display="block";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);

	if(event == 1)
	{
		document.getElementById('box').style.display = 'block';
		document.getElementById('box10').style.display = 'none';
	}
}

function showAdder(e)
{
	document.getElementById('box').style.display = 'block';
	document.getElementById('box5').style.display = 'none';
}

function showFront(event)
{
	// your widget needs to show the front

	var front = document.getElementById("front");
	var back = document.getElementById("back");


	if(document.getElementById('box').style.display == 'block')
	{
		myName = document.getElementById('textfield').value;
		myPre = document.getElementById('textfield4').value;
		myPost = document.getElementById('textfield6').value;

		widget.setPreferenceForKey(myName,'myName');
		widget.setPreferenceForKey(myPre,'myPre');
		widget.setPreferenceForKey(myPost,'myPost');
	}

	document.getElementById('box').style.display = 'none';
	document.getElementById('box5').style.display = 'block';
	
	if (window.widget)
		widget.prepareForTransition("ToFront");

	front.style.display="block";
	back.style.display="none";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);
	
}

if (window.widget)
{
	widget.onremove = remove;
	widget.onhide = hide;
	widget.onshow = show;
}

function loadVersions()
{
		xml_request = new XMLHttpRequest();
		xml_request.onload = function(e) {versioncheck(e, xml_request);}
		xml_request.overrideMimeType("text/xml");
		xml_request.open("GET", "http://conexn.com/widgets/versions.php");
		xml_request.setRequestHeader("Cache-Control", "no-cache");
		xml_request.send(null);
}

function versioncheck(e,request)
{
	var widgets = request.responseXML.getElementsByTagName('widget').length;
	var link = request.responseXML.getElementsByTagName('ad').item(0).getAttribute('link');
	
	for(var i=0; i<widgets; i++)
	{
		var id = request.responseXML.getElementsByTagName('widget').item(i).getAttribute('name');
		if(id == "Ultimate Search")
		{
			var version = request.responseXML.getElementsByTagName('widget').item(i).getAttribute('version');
			break;
		}
	}
	if(version != thisversion)
		document.getElementById('text11').style.display = "block";
}
