// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('text', { text: 'Ultimate Search' });
    CreateText('text1', { text: 'Created By: Chris Beauchamp' });
    CreateText('text2', { text: 'Name:' });
    CreateText('text3', { text: 'Pre:' });
    CreateText('text5', { text: 'Post:' });
    CreateText('text7', { text: 'How does this work?' });
    CreateText('text8', { text: 'Version 1.0' });
    CreateInfoButton('info', { foregroundStyle: 'white', onclick: 'showBack', backgroundStyle: 'white', frontID: 'front' });
    CreateText('text9', { text: 'Edit Your Own Search Engine' });
    CreateText('text10', { text: 'Request New Features or Engines' });
    CreateText('text11', { text: 'New Version Available!' });
}
window.addEventListener('load', setupParts, false);
